In [2]:
import pandas as pd
DATA = 'data/data.csv'

In [7]:
df = pd.read_csv(DATA, sep=';')

### What does the data like

In [9]:
df.sample(10)

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
2500,1,44,1,9085,1,39,150.0,6,5,4,...,1,6,16,5,13.375000,0,12.4,0.5,1.79,Graduate
2423,1,39,1,9003,1,1,133.1,1,1,37,...,0,4,8,0,0.000000,0,16.2,0.3,-0.92,Dropout
586,1,17,1,9085,1,1,120.0,1,38,19,...,0,5,7,5,13.200000,0,7.6,2.6,0.32,Graduate
2891,1,39,1,9991,0,1,150.0,1,3,1,...,0,5,6,0,0.000000,0,12.4,0.5,1.79,Dropout
2097,1,1,2,9238,1,1,100.0,1,38,1,...,0,6,6,6,12.000000,0,12.4,0.5,1.79,Graduate
158,1,1,3,9238,1,1,125.0,1,19,1,...,0,6,9,6,11.833333,0,9.4,-0.8,-3.12,Graduate
2303,1,18,5,9119,1,1,136.0,1,3,2,...,0,5,9,5,14.714286,0,12.4,0.5,1.79,Enrolled
2174,1,43,1,9238,1,1,120.0,1,1,38,...,6,11,14,11,12.750000,0,13.9,-0.3,0.79,Graduate
2022,1,17,4,171,1,1,133.1,1,38,38,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
2412,2,39,2,9991,0,1,150.0,1,37,37,...,1,5,10,4,12.500000,0,9.4,-0.8,-3.12,Enrolled

### What is the shape and structure

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4424 non-null   int64
 1   Application mode                                4424 non-null   int64
 2   Application order                               4424 non-null   int64
 3   Course                                          4424 non-null   int64
 4   Daytime/evening attendance	                     4424 non-null   int64
 5   Previous qualification                          4424 non-null   int64
 6   Previous qualification (grade)                  4424 non-null   float64
 7   Nacionality                                     4424 non-null   int64
 8   Mother's qualification                          4424 non-null   int64
 9   Father's qualification                          4424 non-null   int64
 10  Mother's occupation                             4424 non-null   int64
 11  Father's occupation                             4424 non-null   int64
 12  Admission grade                                 4424 non-null   float64
 13  Displaced                                       4424 non-null   int64
 14  Educational special needs                       4424 non-null   int64
 15  Debtor                                          4424 non-null   int64
 16  Tuition fees up to date                         4424 non-null   int64
 17  Gender                                          4424 non-null   int64
 18  Scholarship holder                              4424 non-null   int64
 19  Age at enrollment                               4424 non-null   int64
 20  International                                   4424 non-null   int64
 21  Curricular units 1st sem (credited)             4424 non-null   int64
 22  Curricular units 1st sem (enrolled)             4424 non-null   int64
 23  Curricular units 1st sem (evaluations)          4424 non-null   int64
 24  Curricular units 1st sem (approved)             4424 non-null   int64
 25  Curricular units 1st sem (grade)                4424 non-null   float64
 26  Curricular units 1st sem (without evaluations)  4424 non-null   int64
 27  Curricular units 2nd sem (credited)             4424 non-null   int64
 28  Curricular units 2nd sem (enrolled)             4424 non-null   int64
 29  Curricular units 2nd sem (evaluations)          4424 non-null   int64
 30  Curricular units 2nd sem (approved)             4424 non-null   int64
 31  Curricular units 2nd sem (grade)                4424 non-null   float64
 32  Curricular units 2nd sem (without evaluations)  4424 non-null   int64
 33  Unemployment rate                               4424 non-null   float64
 34  Inflation rate                                  4424 non-null   float64
 35  GDP                                             4424 non-null   float64
 36  Target                                          4424 non-null   str
dtypes: float64(7), int64(29), str(1)
memory usage: 1.2 MB

### Is anything missing

In [14]:
df.isnull().sum()

Marital status                                    0
Application mode                                  0
Application order                                 0
Course                                            0
Daytime/evening attendance\t                      0
Previous qualification                            0
Previous qualification (grade)                    0
Nacionality                                       0
Mother's qualification                            0
Father's qualification                            0
Mother's occupation                               0
Father's occupation                               0
Admission grade                                   0
Displaced                                         0
Educational special needs                         0
Debtor                                            0
Tuition fees up to date                           0
Gender                                            0
Scholarship holder                                0
Age at enrollment                                 0
International                                     0
Curricular units 1st sem (credited)               0
Curricular units 1st sem (enrolled)               0
Curricular units 1st sem (evaluations)            0
Curricular units 1st sem (approved)               0
Curricular units 1st sem (grade)                  0
Curricular units 1st sem (without evaluations)    0
Curricular units 2nd sem (credited)               0
Curricular units 2nd sem (enrolled)               0
Curricular units 2nd sem (evaluations)            0
Curricular units 2nd sem (approved)               0
Curricular units 2nd sem (grade)                  0
Curricular units 2nd sem (without evaluations)    0
Unemployment rate                                 0
Inflation rate                                    0
GDP                                               0
Target                                            0
dtype: int64

### What do the number look like statistically

In [16]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Marital status,4424.0,1.178571,0.605747,1.00,1.00,1.000000,1.000000,6.000000
Application mode,4424.0,18.669078,17.484682,1.00,1.00,17.000000,39.000000,57.000000
Application order,4424.0,1.727848,1.313793,0.00,1.00,1.000000,2.000000,9.000000
Course,4424.0,8856.642631,2063.566416,33.00,9085.00,9238.000000,9556.000000,9991.000000
Daytime/evening attendance\t,4424.0,0.890823,0.311897,0.00,1.00,1.000000,1.000000,1.000000
Previous qualification,4424.0,4.577758,10.216592,1.00,1.00,1.000000,1.000000,43.000000
Previous qualification (grade),4424.0,132.613314,13.188332,95.00,125.00,133.100000,140.000000,190.000000
Nacionality,4424.0,1.873192,6.914514,1.00,1.00,1.000000,1.000000,109.000000
Mother's qualification,4424.0,19.561935,15.603186,1.00,2.00,19.000000,37.000000,44.000000
Father's qualification,4424.0,22.275316,15.343108,1.00,3.00,19.000000,37.000000,44.000000
Mother's occupation,4424.0,10.960895,26.418253,0.00,4.00,5.000000,9.000000,194.000000
Father's occupation,4424.0,11.032324,25.263040,0.00,4.00,7.000000,9.000000,195.000000
Admission grade,4424.0,126.978119,14.482001,95.00,117.90,126.100000,134.800000,190.000000
Displaced,4424.0,0.548373,0.497711,0.00,0.00,1.000000,1.000000,1.000000
Educational special needs,4424.0,0.011528,0.106760,0.00,0.00,0.000000,0.000000,1.000000
Debtor,4424.0,0.113698,0.317480,0.00,0.00,0.000000,0.000000,1.000000
Tuition fees up to date,4424.0,0.880651,0.324235,0.00,1.00,1.000000,1.000000,1.000000
Gender,4424.0,0.351718,0.477560,0.00,0.00,0.000000,1.000000,1.000000
Scholarship holder,4424.0,0.248418,0.432144,0.00,0.00,0.000000,0.000000,1.000000
Age at enrollment,4424.0,23.265145,7.587816,17.00,19.00,20.000000,25.000000,70.000000
International,4424.0,0.024864,0.155729,0.00,0.00,0.000000,0.000000,1.000000
Curricular units 1st sem (credited),4424.0,0.709991,2.360507,0.00,0.00,0.000000,0.000000,20.000000
Curricular units 1st sem (enrolled),4424.0,6.270570,2.480178,0.00,5.00,6.000000,7.000000,26.000000
Curricular units 1st sem (evaluations),4424.0,8.299051,4.179106,0.00,6.00,8.000000,10.000000,45.000000
Curricular units 1st sem (approved),4424.0,4.706600,3.094238,0.00,3.00,5.000000,6.000000,26.000000
Curricular units 1st sem (grade),4424.0,10.640822,4.843663,0.00,11.00,12.285714,13.400000,18.875000
Curricular units 1st sem (without evaluations),4424.0,0.137658,0.690880,0.00,0.00,0.000000,0.000000,12.000000
Curricular units 2nd sem (credited),4424.0,0.541817,1.918546,0.00,0.00,0.000000,0.000000,19.000000
Curricular units 2nd sem (enrolled),4424.0,6.232143,2.195951,0.00,5.00,6.000000,7.000000,23.000000
Curricular units 2nd sem (evaluations),4424.0,8.063291,3.947951,0.00,6.00,8.000000,10.000000,33.000000
Curricular units 2nd sem (approved),4424.0,4.435805,3.014764,0.00,2.00,5.000000,6.000000,20.000000
Curricular units 2nd sem (grade),4424.0,10.230206,5.210808,0.00,10.75,12.200000,13.333333,18.571429
Curricular units 2nd sem (without evaluations),4424.0,0.150316,0.753774,0.00,0.00,0.000000,0.000000,12.000000
Unemployment rate,4424.0,11.566139,2.663850,7.60,9.40,11.100000,13.900000,16.200000
Inflation rate,4424.0,1.228029,1.382711,-0.80,0.30,1.400000,2.600000,3.700000
GDP,4424.0,0.001969,2.269935,-4.06,-1.70,0.320000,1.790000,3.510000

### Are there outliers

In [18]:
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
for column in df.columns:
    if df[column].dtype in ['int64', 'float64']:
        plt.figure()
        sns.boxplot(x=df[column])
        plt.title(f'Boxplot of {column}')
        plt.show()